version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_HOST_PORT}:${PGADMIN_PORT}

  redis:
    image: redis:7
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

  teslo-shop-api:
    container_name: teslo-shop-api
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file: .env

volumes:
  redis:
    driver: local
